### ISSUE TITLE
Exception on refresh account

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill-analytics-plugin#45]
Trying to refresh account 8a2bdb21-ec88-4e15-ba60-d534dbbe6770 in Analytics and get the exception below. It appears that there are lots of accounts missing account info in analytics_accounts and I suspect that it's the same cause.

2015-07-01 21:18:50,599 [catalina-exec-1] INFO  c.s.j.a.c.filter.LoggingFilter - 4157 * Server in-bound request
4157 > PUT http://killbill-uat1.snc1:8080/plugins/killbill-analytics/8a2bdb21-ec88-4e15-ba60-d534dbbe6770
4157 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
4157 > user-agent: curl/7.30.0
4157 > host: killbill-uat1.snc1:8080
4157 > accept: */*

2015-07-01 21:18:50,720 [Thread-6] INFO  o.k.b.p.j.a.1.0.2.SNAPSHOT - Starting Analytics refresh for account 8a2bdb21-ec88-4e15-ba60-d534dbbe6770
2015-07-01 21:18:50,961 [catalina-exec-1] WARN  o.k.b.j.m.RuntimeExceptionMapper - Exception : null
2015-07-01 21:18:50,961 [catalina-exec-1] WARN  o.k.b.j.mappers.ExceptionMapperBase - Bad request
java.lang.NullPointerException: null
	at org.killbill.billing.plugin.analytics.dao.model.BusinessPaymentBaseModelDao.<init>(BusinessPaymentBaseModelDao.java:415)
	at org.killbill.billing.plugin.analytics.dao.model.BusinessPaymentBaseModelDao.<init>(BusinessPaymentBaseModelDao.java:366)
	at org.killbill.billing.plugin.analytics.dao.model.BusinessPaymentVoidModelDao.<init>(BusinessPaymentVoidModelDao.java:47)
	at org.killbill.billing.plugin.analytics.dao.model.BusinessPaymentBaseModelDao.create(BusinessPaymentBaseModelDao.java:203)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessPaymentFactory.createBusinessPayments(BusinessPaymentFactory.java:73)
	at org.killbill.billing.plugin.analytics.dao.BusinessInvoiceAndPaymentDao.createBusinessPojos(BusinessInvoiceAndPaymentDao.java:108)
	at org.killbill.billing.plugin.analytics.dao.BusinessInvoiceAndPaymentDao.update(BusinessInvoiceAndPaymentDao.java:85)
	at org.killbill.billing.plugin.analytics.dao.AllBusinessObjectsDao.update(AllBusinessObjectsDao.java:59)
	at org.killbill.billing.plugin.analytics.api.user.AnalyticsUserApi.rebuildAnalyticsForAccount(AnalyticsUserApi.java:108)
	at org.killbill.billing.plugin.analytics.http.AnalyticsServlet.doPut(AnalyticsServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.killbill.billing.plugin.analytics.http.ServletRouter.forward(ServletRouter.java:118)
	at org.killbill.billing.plugin.analytics.http.ServletRouter.doPut(ServletRouter.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at sun.reflect.GeneratedMethodAccessor1448.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1$1.execute(ContextClassLoaderHelper.java:83)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1.invoke(ContextClassLoaderHelper.java:80)
	at com.sun.proxy.$Proxy133.service(Unknown Source)
	at org.killbill.billing.osgi.http.OSGIServlet.serviceViaPlugin(OSGIServlet.java:82)
	at org.killbill.billing.osgi.http.OSGIServlet.doPut(OSGIServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.killbill.billing.jaxrs.resources.PluginResource.serviceViaOSGIPlugin(PluginResource.java:179)
	at org.killbill.billing.jaxrs.resources.PluginResource.serviceViaOSGIPlugin(PluginResource.java:165)
	at org.killbill.billing.jaxrs.resources.PluginResource.doPUT(PluginResource.java:148)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.groupon.killbill.gkb.filters.GKBTenantFilter.doFilter(GKBTenantFilter.java:64)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1015)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 21:18:50,962 [catalina-exec-1] INFO  c.s.j.a.c.filter.LoggingFilter - 4157 * Server out-bound response
4157 < 400
4157 < Content-Type: application/json
4157 <

**Comment by pierre** [comment]
It looks like we're missing a null check [here](https://github.com/killbill/killbill-analytics-plugin/blob/master/src/main/java/org/killbill/billing/plugin/analytics/dao/model/BusinessPaymentBaseModelDao.java#L415).
