### ISSUE TITLE
NPE in BusinessTagModelDao

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-analytics-plugin#69]
Seen in the field (unsure how to reproduce it):

```
2017-02-23T10:47:00,184+0000 lvl='ERROR', log='KillbillLogWriter', th='Thread-26', xff='', rId='', aRId='14616', tRId='2125', Fatal NotificationQ dispatch error, data corruption...
org.apache.felix.log.LogException: org.killbill.notificationq.NotificationQueueException: java.lang.NullPointerException
	at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:205)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at org.killbill.billing.plugin.analytics.dao.model.BusinessTagModelDao.<init>(BusinessTagModelDao.java:132)
	at org.killbill.billing.plugin.analytics.dao.model.BusinessAccountTagModelDao.<init>(BusinessAccountTagModelDao.java:39)
	at org.killbill.billing.plugin.analytics.dao.model.BusinessTagModelDao.create(BusinessTagModelDao.java:54)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessTagFactory.createBusinessTags(BusinessTagFactory.java:67)
	at org.killbill.billing.plugin.analytics.dao.BusinessTagDao.update(BusinessTagDao.java:45)
	at org.killbill.billing.plugin.analytics.dao.AllBusinessObjectsDao.update(AllBusinessObjectsDao.java:65)
	at org.killbill.billing.plugin.analytics.AnalyticsListener.handleAnalyticsJob(AnalyticsListener.java:252)
	at org.killbill.billing.plugin.analytics.AnalyticsListener.access$100(AnalyticsListener.java:66)
	at org.killbill.billing.plugin.analytics.AnalyticsListener$1.handleReadyNotification(AnalyticsListener.java:137)
	at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
	... 10 common frames omitted
```

**Comment by beccagaspard** [comment]
We are experiencing the same error... looks like the `__PARK__` tags w/ tag definition id of `00000000-0000-0001-0000-000000000001` are the culprit.  Assuming these are created when `org.killbill.invoice.enabled=false` is set.  Updating https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/tag/api/DefaultTagUserApi.java#L78 to set `includeSystemTags` to `true` in `getTagDefinitions` call corrects the issue in our environment...  But this will result in the  `__PARK__` tags being inserted into the `analytics_account_tags` table.  Is this the correct approach?  If so, I can open a pull request in the killbill project.  Let me know! 😀

**Comment by sbrossie** [comment]
@beccagaspard Yes, i think changing the `includeSystemTags` flag from `false` to `true` would solve the analytics problem. However i am not sure we always want to return the `PARK_TAG_DEFINITION_ID`, so maybe we need to enhance our [TagUserApi](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/util/api/TagUserApi.java#L43) to decide on the behavior?

@pierre Any thoughts?

**Comment by pierre** [comment]
I'm curious why we don't return system tags today... To make this even more confusing, `DefaultTagInternalApi` does return them (unused API though).

I would be inclined to return them.

**Comment by beccagaspard** [comment]
Is this approach ok?  Just overloaded `getTagDefinitions` to optionally accept `includeSystemTags` as a parameter. 

https://github.com/killbill/killbill/pull/787
https://github.com/killbill/killbill-api/pull/32
https://github.com/killbill/killbill-analytics-plugin/pull/72
