### ISSUE TITLE
Incorrect use a catalog api leads to `Could not find a plan matching spec`

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-analytics-plugin#70]
The issue was reported on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/azim%7Csort:relevance/killbilling-users/i9HESgr_RSI/mPxXBSViAwAJ), and i could easily reproduce it:

* Define a plan in catalog V1 and create the subscription -> OK
* Define a catalog with V2 without that plan -> Ok
* Move clock to reach next invoicing period ->  analytics plugin throws stack trace

```
org.apache.felix.log.LogException: org.killbill.billing.catalog.api.CatalogApiException: Could not find a plan matching spec: (plan: 'MALTESTPRODUCT_MONTHLY', product: 'undefined', billing period: 'undefined', pricelist 'undefined')
        at org.killbill.billing.catalog.VersionedCatalog.findCatalogPlanEntry(VersionedCatalog.java:186)
        at org.killbill.billing.catalog.VersionedCatalog.findPlan(VersionedCatalog.java:301)
        at org.killbill.billing.catalog.VersionedCatalog.findPhase(VersionedCatalog.java:332)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessFactoryBase.getPlanPhaseFromInvoiceItem(BusinessFactoryBase.java:381)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessContextFactory.getPlanPhaseFromInvoiceItem(BusinessContextFactory.java:401)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessInvoiceFactory.createBusinessInvoiceItem(BusinessInvoiceFactory.java:244)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessInvoiceFactory.createBusinessInvoiceItem(BusinessInvoiceFactory.java:190)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessInvoiceFactory.access$000(BusinessInvoiceFactory.java:65)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessInvoiceFactory$1.call(BusinessInvoiceFactory.java:117)
        at org.killbill.billing.plugin.analytics.dao.factory.BusinessInvoiceFactory$1.call(BusinessInvoiceFactory.java:114)
```

**Comment by sbrossie** [comment]
See discussion a out catalog api in [this comment](https://github.com/killbill/killbill/issues/56#issuecomment-291654870)

**Comment by sbrossie** [comment]
The [fix above](https://github.com/killbill/killbill-analytics-plugin/commit/a74fa0f1156abab93939edc9d6bc220a322ea0b6) is a partial fix: It allows to pass the `subscriptionStartDate`, but analytics code converts that date from `LocalDate` to `DateTime` using `toDateTimeAtStartOfDay`.


When creating new catalog entries and right away subscribing to plans, we have a lot of chances to hit this problem -- reported on the mailing list several times.

I am [suggesting to make a fix at KB core level](https://github.com/killbill/killbill/issues/760#issuecomment-320808796)

**Comment by Arulraj12** [comment]
Hi,
Is this issue still open in 0.18.14?
If there, what is the workaround solution and how long need to wait for subscription like 30 second sleep?

**Comment by sbrossie** [comment]
I believe this has been fixed, but if this is not the case, please provide
a scenario we can use to reproduce -- test against 0.18.17.
