### ISSUE TITLE
Exception when running integration tests

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-analytics-plugin#94]
When running the test `test_create_an_entitlement_with_addOn_products`, the following stack trace was seen:

```
2019-05-08T00:36:15,960+0000 lvl='ERROR', log='AnalyticsListener', th='analytics_notifications-th', xff='', rId='', tok='46818f96-7583-44f2-9a8b-3544559155b9', aRId='18467', tRId='1249', Unable to process event
org.killbill.billing.plugin.analytics.AnalyticsRefreshException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Object id=bedb905c-38e4-47b0-a989-c8e7f534c829 type=BUNDLE doesn't belong to tenant id=d614a2c7-a024-42b7-8f74-62f72acdd112
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessBundleFactory.createBusinessBundles(BusinessBundleFactory.java:115)
	at org.killbill.billing.plugin.analytics.dao.BusinessSubscriptionTransitionDao.update(BusinessSubscriptionTransitionDao.java:70)
	at org.killbill.billing.plugin.analytics.dao.AllBusinessObjectsDao.update(AllBusinessObjectsDao.java:57)
	at org.killbill.billing.plugin.analytics.AnalyticsListener.handleAnalyticsJob(AnalyticsListener.java:292)
	at org.killbill.billing.plugin.analytics.AnalyticsListener.access$200(AnalyticsListener.java:70)
	at org.killbill.billing.plugin.analytics.AnalyticsListener$1.handleReadyNotification(AnalyticsListener.java:143)
	at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:219)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueueHandler.call(Dispatcher.java:137)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueueHandler.call(Dispatcher.java:105)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Object id=bedb905c-38e4-47b0-a989-c8e7f534c829 type=BUNDLE doesn't belong to tenant id=d614a2c7-a024-42b7-8f74-62f72acdd112
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessBundleFactory.createBusinessBundles(BusinessBundleFactory.java:111)
	... 16 common frames omitted
```

**Comment by sbrossie** [comment]
Closed as we diagnosed the [bug](https://github.com/killbill/killbill/issues/1136) was in killbill core
